#!/bin/sh
cru a CheckIfHome "* * * * * /jffs/scripts/devicechk.sh"
cru a CheckIfHome10 "* * * * * sleep 10; /jffs/scripts/devicechk.sh"
cru a CheckIfHome20 "* * * * * sleep 20; /jffs/scripts/devicechk.sh"
cru a CheckIfHome30 "* * * * * sleep 30; /jffs/scripts/devicechk.sh"
cru a CheckIfHome40 "* * * * * sleep 40; /jffs/scripts/devicechk.sh"
cru a CheckIfHome50 "* * * * * sleep 50; /jffs/scripts/devicechk.sh"
